title: ToCalibrate
description: 
theme: just-the-docs

url: https://tocalibrate.github.io/

aux_links:
  Calibrate Repository: https://github.com/ToCalibrate/tocalibrate.github.io

aux_links_new_tab: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

remote_theme: just-the-docs/just-the-docs

nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: grey-lt
  important:
    title: Important
    color: green
  note:
    title: Note
    color: grey-dk
  tip:
    title: Tip
    color: blue
  caution:
    title: Caution
    color: red
  error:
    color: pink
  attention:
    title: Attention
    color: purple

plugins:
  - jekyll-default-layout
