title: ToCalibrate
description: 
theme: just-the-docs

url: https://tocalibrate.github.io/

aux_links:
  Calibrate Repository: https://github.com/ToCalibrate/tocalibrate.github.io
plugins:
  - jekyll-default-layout